# 要处理的作业ID
homework_id = "1"

# 问题列表配置
# 格式遵循 "chapter X: 问题1ID,问题2ID,问题3ID(子问题1ID)(子问题2ID),..."
# 每行代表一个章节的问题
# 即使问题列表中包含所有子问题，子问题ID也需要全部列出。例如，如果问题1有子问题a和b，问题列表应该是"1(a)(b)"而不是"1"
# 子问题ID应该按照它们在问题描述中出现的顺序排列
# 如果一个问题没有子问题，应省略子问题ID
# 请注意不要使用中文标点符号
problem_list = """
chapter 1: 1,2,3
chapter 2: 1,2(1)(2),3
"""

# OpenReview配置
[openreview]
username = "your_email@example.com"
password = "your_password"
venue_id = "PKU.edu/2025/Spring/AIM"

# LLM配置
[llm]
base_url = "https://base/url/to/llm"
api_key = "your_openai_api_key"
model = "gpt-4-turbo"
temperature = 0.5
max_trials = 5

# 目录配置
[paths]
# 包含参考资料的目录路径：问题描述和参考答案
reference_materials = "../reference_materials"
# 包含处理后提交内容的目录路径
processed_submissions = "../processed_submissions"
# 包含原始提交内容的目录路径
raw_submissions = "../raw_submissions"
# 包含与LLM交互的可读标记日志的目录路径
mark_logs = "../mark_logs"
# 包含人工编辑标记的目录路径
human_marks = "../human_marks"

# 标记提示模板
[prompts]
# 用于没有子问题的题目的模板
# 可用占位符：
# - {problem_description}: 完整的问题描述
# - {reference_answer}: 参考答案
# - {student_answer}: 学生提交的答案
# 该模板用于评估没有子问题的完整题目
no_subproblem_template = """
你是《AI中的数学》课程助教，负责批改学生的作业。请按照以下内容要求对学生的作业进行批改：
# 问题描述
{problem_description}

# 参考答案
{reference_answer}

# 学生答案
{student_answer}

请提供详细的反馈，需要包含以下内容：
1. 对学生解题思路和推理过程的简单总结
2. 指出任何概念性错误或证明错误（如果学生答案的确有这个问题，否则不要提及）
3. 指出可能令人感到困惑的表述（如果学生答案的确有这个问题，否则不要提及）
4. 建设性的改进建议（如果学生答案的确有这个问题，否则不要提及）

如果这个题目是一个证明题或者计算题，还需要检查推理的每一步是否正确，或者计算的每一步是否正确。

请注意，尽管学生的答案会和参考答案有所不同，但这不意味着学生的答案就是错误的。如果偏差较大，意味着学生可能有不同的解题思路，这也是可以接受的，这个时候，请你直接评估该学生的解答是否合理，不要被参考答案所影响。

如果这个题目的描述或者答案涉及到图片，作为语言模型，你不能看到或者理解图片内容，所以请表明你无法处理图片内容。

请使用markdown格式回答，所有标题使用单独一行加粗而非井号，只需要批改，不需要给分数或者评级。
"""

# 用于包含子问题的题目的初轮模板
# 可用占位符：
# - {problem_description}: 整体问题描述（不包含所有子问题）
# - {subproblem_nums}: 需要评估的子问题数量
# 该模板用于开始评估包含多个子问题的题目的第一条消息，在评估任何具体子问题之前
subproblem_first_round_template = """
你是《AI中的数学》课程助教，负责批改学生的作业，这份作业包含多个子问题。

这是批改的第一轮，你将收到问题总描述（不包含子问题），稍后你将被要求分别批改每个子问题。

# 问题总描述（不包含子问题）
{problem_description}

该问题有{subproblem_nums}个子问题。

请确认你已收到问题描述并准备好批改。接下来的每一轮，你将批改一个子问题。
"""

# 用于评估单个子问题的模板
# 可用占位符：
# - {problem_description}: 该具体子问题的描述
# - {reference_answer}: 该子问题的参考答案
# - {student_answer}: 该子问题的学生答案
# - {subproblem_id}: 子问题的标识符（例如，“1”，“2”，“a”，“b”）
# 该模板用于第一轮之后的每个子问题，允许详细评估多部分问题的各个部分
subproblem_round_template = """
你现在正在批改子问题 {subproblem_id}。

# 子问题描述
{problem_description}

# 参考答案
{reference_answer}

# 学生答案
{student_answer}

请提供详细的反馈，需要包含以下内容：
1. 对学生解题思路和推理过程的简单总结
2. 指出任何概念性错误或证明错误（如果学生答案的确有这个问题，否则不要提及）
3. 指出可能令人感到困惑的表述（如果学生答案的确有这个问题，否则不要提及）
4. 建设性的改进建议（如果学生答案的确有这个问题，否则不要提及）

如果这个题目是一个证明题或者计算题，还需要检查推理的每一步是否正确，或者计算的每一步是否正确。

请注意，尽管学生的答案会和参考答案有所不同，但这不意味着学生的答案就是错误的。如果偏差较大，意味着学生可能有不同的解题思路，这也是可以接受的，这个时候，请你直接评估该学生的解答是否合理，不要被参考答案所影响。

如果这个题目的描述或者答案涉及到图片，作为语言模型，你不能看到或者理解图片内容，所以请表明你无法处理图片内容。

请使用markdown格式回答，所有标题使用单独一行加粗而非井号，只需要批改，不需要给分数或者评级。
"""

# LLM标记文件模板
# 这是在反馈内容之前插入到LLM生成的标记文件顶部的内容
llm_mark_template = """
以下是由AI助教对您的作业生成的自动批改反馈。请注意，这是由大语言模型生成的初步反馈，最终成绩和更详细的反馈可能会有所不同。

---
"""

# 人工标记文件模板
# 这是在反馈内容之前插入到人工可编辑标记文件顶部的内容
# 你有两种人工标记选项：修改LLM生成的标记或提供LLM生成标记的修订版
# 该模板用于后者情况，其中人工标记是LLM生成标记的修订版
# 如果你也上传LLM标记，建议使用修订模板进行人工标记，否则OpenReview可能会超出长度限制
human_mark_template = """
以下是对AI助教生成的自动批改反馈的人工修订。请注意，这一人工修订仅包含对AI批改的修改，不包含完整的批改反馈。

---
"""
