name: Cross-Platform Integration Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: AIM-chatbot
        python-version: 3.11
        auto-activate-base: false

    - name: Install dependencies (Unix)
      if: runner.os != 'Windows'
      shell: bash -l {0}
      run: |
        pip install -r requirements.txt

    - name: Install dependencies (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        pip install -r requirements.txt

    - name: Run tests
      shell: bash -l {0}
      run: |
        cd src
        python RAG.py
        streamlit run app.py
